### ISSUE TITLE
Rule idea: `dollar-variable-place`

### ISSUE THREAD

**Issue by evilebottnawi** [kristerkari/stylelint-scss#103]
Allow and disallow inside block or out side
- `dollar-variable-place: "outside-declaration-block"`

Valid:
```scss
$color: red;

a {
  color: $color;
}
```
Invalid:
```scss
a {
  $color: red;
  color: $color;
}
```
- `dollar-variable-place: "inside-declaration-block"`

Invalid:
```scss
$color: red;

a {
  color: $color;
}
```
Valid:
```scss
a {
  $color: red;
  color: $color;
}
```
Maybe best name for rule and options. I can do PR.
