### ISSUE TITLE
Rule idea: value-no-non-variable

### ISSUE THREAD

**Issue by dryoma** [kristerkari/stylelint-scss#13]
Inspired by #4 

SCSS-lint (sorry to bring it up again; can't help it, since it's a functioning tool and the one seems the most popuar) has [VariableForProperty](https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md#variableforproperty) rule. It does almost the same, except it forces the policy not on _value types_ (like @davidtheclark proposed), but for _property names_ and is more general.

I just thought that in the future users would want something similar to `color-no-non-variable`, but for fonts and other types of values. Wouldn't it be less redundant to make a general thing like `value-no-non-variable` and make it accept an array of value types/property names?

As for checking those variables values, I think that is more of a Sass compiler's job.

**Comment by kristerkari** [comment]
Sounds good. I've added this to the milestone for a release after 1.0.

**Comment by jeddy3** [comment]
Perhaps this is already achievable with [`property-value-whitelist`](https://github.com/stylelint/stylelint/tree/master/src/rules/property-value-whitelist), it's pretty powerful rule e.g.

```js
"property-value-whitelist": {
  "font": ["/^$/"]
  "color": ["/^$/"]
}
```

**Comment by dryoma** [comment]
@jeddy3 if we stick to property names only, then it seems so. Yet the initial proposal was to control all values of specified type:

```css
// bad
.foo { color: pink; background: #fff; }

// good
$some-color: pink;
$some-background: #fff;
.foo { color: $some-color; background: $some-backgorund; }
```
I'd allow myself to elaborate the example like this:

```css
// good
$some-color: pink;
$some-background: #fff;
.foo {
  color: $some-color;
  background: url("...") center no-repeat $some-backgorund; // cause there can be more than color in a background value
}
```
@davidtheclark am I right in the assumtion, that only the color-type values are to be forced to be variables with that rule, not the whole values of properties?
