### ISSUE TITLE
Request new rule: Declare properties before nested rules

### ISSUE THREAD

**Issue by spawnia** [kristerkari/stylelint-scss#165]
Properties in a rule should always be declared before nested rules. This is because the properties for the element itself are most important to see first.

This would be considered a violation:

```css
.bar{
  color: red;
  .foo {
    color: pink;
  }
}
```
This would be considered OK
```css
.bar{
  .foo {
    color: pink;
  }
  color: red;
}
```
