### ISSUE TITLE
`double-slash-comment-empty-line-before` except first-nested doesn't work

### ISSUE THREAD

**Issue by spaceninja** [kristerkari/stylelint-scss#183]
From my config:

```
        "scss/double-slash-comment-empty-line-before": [ "always", {
            except: ["first-nested"],
            ignore: ["between-comments", "stylelint-commands"],
        } ],
```

And the following code throws an error:

```css
.form-single-array {

    // nested form items
    .form-group {
        color: red;
    }
}
```

If I'm reading the rule correctly, the `except: ["first-nested"]` should cause that CSS to pass validation. Am I doing something wrong?
