### ISSUE TITLE
`@include` throwing `at-rule-no-unknown`

### ISSUE THREAD

**Issue by woodyrew** [kristerkari/stylelint-scss#196]
I'm getting the following error when using `@include`
![2018-01-24_1a68](https://user-images.githubusercontent.com/1902064/35361140-1c79e6fe-0158-11e8-8a41-082eb9a7b769.png)

The configuration `.stylelintrc`
```yaml
plugins:
  - stylelint-scss
extends:
  - stylelint-config-standard
```

Is this an error or have I configured something wrong?
Thanks

**Comment by kristerkari** [comment]
Hmm... I'm not sure which rules `stylelint-config-standard` includes, but you have to use the SCSS version of the rule, so this should help:

```yaml
rules:
  at-rule-no-unknown: null
  scss/at-rule-no-unknown: true
```
