### ISSUE TITLE
Rule to enforce nesting of elements

### ISSUE THREAD

**Issue by hisuwh** [kristerkari/stylelint-scss#197]
I want stylelint to complain if I do this:

```css
.something .something-else {
    width: 100px;
}
```

And be happy if I do this:
```css
.something {
    .something-else {
        width: 100px;
    }
}
```

Much like sass-lint's [force-element-nesting](https://github.com/sasstools/sass-lint/blob/master/docs/rules/force-element-nesting.md)
