### ISSUE TITLE
Rule idea: Require interpolation when string variables are used as custom identiefiers

### ISSUE THREAD

**Issue by kristerkari** [kristerkari/stylelint-scss#2]
Some CSS features like animations allow the user to specify a custom identifier for animation name. 

So if you have `animation-name` as a string inside a Sass variable, you need to use interpolation to get rid of the quotes. There could be a rule that requires interpolation to be used in those cases.

So this SCSS:

```scss
$var: "my-anim";

.class {
  animation-name: $var;
}

@keyframes $var {
}
```

...gets compiled to:

```css
.class {
  animation-name: "my-anim";
}

@keyframes "my-anim" {}
```

Which does not work. You need to use interpolation to get rid of the quotes:

```scss
$var: "my-anim";

.class {
  animation-name: #{$var};
}

@keyframes #{$var} {
}
```

...and that gets compiled to:

```css
.class {
  animation-name: my-anim;
}

@keyframes my-anim {}
```

More info:
- `animation-name` - MDN: https://developer.mozilla.org/en-US/docs/Web/CSS/animation-name
- custom CSS identifier - MDN: https://developer.mozilla.org/en-US/docs/Web/CSS/custom-ident
