### ISSUE TITLE
add @at-root indentation support

### ISSUE THREAD

**Issue by AndyOGo** [kristerkari/stylelint-scss#206]
By enabling the intrinsic [**indentation**](https://stylelint.io/user-guide/rules/indentation/) rule I get indentation errors for using SASS's `@at-root` syntax.
Unfortunately I can't ignore certain @-rules over there. So I suppose to add a SCSS specific identation rule.

The following code errors.

````scss
.foo {
  text-align: center;

  @at-root .foo--left,
  .text-left & {
    text-align: left;
  }
}
````

**Comment by kristerkari** [comment]
Thanks @AndyOGo! Hmm.. this is a tricky one. I would like to avoid creating a SCSS specific indentation rule if possible. 

Would it be possible for you to write the selector in a different way (nesting) to avoid the indentation error?

**Comment by AndyOGo** [comment]
@kristerkari 
Thanks for your quick answer.
Sure, that's easy to change. Just not as nice.

Splitting them like, works:
````scss
.foo {
  text-align: center;

  @at-root .foo--left {
    text-align: left;
  }

  .text-left & {
    text-align: left;
  }
}
````

Though, I decided to just disable it:
````scss
.foo {
  text-align: center;

  /* stylelint-disable indentation */
  @at-root .foo--left,
  .text-left & {
    text-align: left;
  }
  /* stylelint-enable indentation */
}
````
