### ISSUE TITLE
[question] `scss/no-duplicate-dollar-variables`

### ISSUE THREAD

**Issue by evilebottnawi** [kristerkari/stylelint-scss#244]
Example:
```scss
.btn {
    $new-color: $color;

    @if (lightness($background) < 75%) {
      $new-color: $background;
    }

    color: $new-color;
}
```

Looks like rule don't look on context, just search same name and all. It is expected behaviour?
