### ISSUE TITLE
stylelint-scss selector-no-union-class-name breaks entire stylelint process

### ISSUE THREAD

**Issue by jantimon** [kristerkari/stylelint-scss#345]
Reproduction css example:

```css

@mixin demo() {
   @content;
}

.a-selector {

  @include demo() { 
      button:hover & {
  	background:purple
     }
  }

}
```

If you run this code against the `selector-no-union-class-name` test it will crash the entire process.

I did some research and found out that the reason is that the parent of `button:hover & {` is `@include demo() { ` and therefore there is no `selector` property for the parent in this line:

https://github.com/kristerkari/stylelint-scss/blob/147b44cf10725fbf7b08a33885a6f7b7b8df4bb9/src/rules/selector-no-union-class-name/index.js#L38

![undefinedSelector](https://user-images.githubusercontent.com/4113649/61312587-fb382700-a7f8-11e9-8a07-715f8b7982ae.png)

The good news is that the `selector` is in the `parent` of the `parent`:
![parent_parent](https://user-images.githubusercontent.com/4113649/61312971-c7a9cc80-a7f9-11e9-83c2-91ea06115061.png)

So probably we could just iterate over the parents until we find the closest `parent` with a selector` property.
If none can be found we just skip the test.

What do you think?
