### ISSUE TITLE
Support new Sass module syntax at-rules

### ISSUE THREAD

**Issue by mirisuzanne** [kristerkari/stylelint-scss#366]
The new syntax ([now in beta](https://www.npmjs.com/package/sass/v/1.23.0-module.beta.1), planned for [release on Oct 1](https://github.com/sass/sass/blob/master/accepted/module-system.md#timeline)) replaces `@import` with `@forward` and `@use`. For now, I'm overriding stylelint-css with:

```yaml
rules:
  at-rule-no-unknown: false
  scss/at-rule-no-unknown:
    - true
    - ignoreAtRules:
      - use
      - forward
```
