### ISSUE TITLE
`at-mixin-pattern` buggy

### ISSUE THREAD

**Issue by evilebottnawi** [kristerkari/stylelint-scss#38]
```json
{
  "rules": {
    "scss/at-mixin-pattern": "^[a-z][a-z0-9-_]*[a-z0-9]$",
  },
  "plugins": [
        "stylelint-scss"
    ]
}
```
```scss
@mixin text-overflow-line-clamp(
    $lines-to-show: 1,
    $background: $body-bg,
    $color: $text-color,
    $line-height: $line-height-base,
    $font-size: $font-size-base
) {
  // Some logic
}
```
```shell
1:1	⚠  Expected @mixin name to match specified pattern (scss/at-mixin-pattern) [stylelint]
```
