### ISSUE TITLE
Use @use rule's namespace will result in a font-family-no-missing-generic-family-keyword error.

### ISSUE THREAD

**Issue by kimulaco** [kristerkari/stylelint-scss#387]
Even if sans-serif is specified, using namespace will result in an error.

"@use" isn't a CSS standard feature, so you may need a new "scss/font-family-no-missing-generic-family-keyword" rule.

```scss
// src/scss/_font.scss
$font-family-default: Arial, sans-serif;
```

```scss
// src/scss/_button.scss
@use "font" as font;

.button {
  font-family: font.$font-family-default;
}
```

```
src/scss/_button.scss
 4:16  ✖  Unexpected missing generic font family   font-family-no-missing-generic-family-keyword
```

[@use - Choosing a Namespace](https://sass-lang.com/documentation/at-rules/use#choosing-a-namespace)
