### ISSUE TITLE
[feature request]: `selector-nest-combinators` option `least`

### ISSUE THREAD

**Issue by JounQin** [kristerkari/stylelint-scss#390]
First case which should emit error:

```scss
.a {
  &.b {
    color: red;
  }
}
```

Second case which should be allowed:
```scss
.a {
  &.b {
    color: red;
  }

  .c {
    font-size: 16px;
  }
}
```

@kristerkari What do you think?

**Comment by kristerkari** [comment]
Hi @JounQin and sorry for the late reply. 

I'm not totally sure what's the use case for having such option, could you provide another example that would maybe be related to some issue that you are having with the rule? 

Also, why is the option called `least`? Is that a good name to describe it?

I'm totally ok with adding the option, but I just need to understand it properly first.

**Comment by JounQin** [comment]
@kristerkari We don't want to add redundant nested block in our team, so current option `always | never` is both too strict and unreasonable for us.

```scss
// input
.a {
  &.b {
    color: red;
  }
}

// expected output
.a.b {
  color: red;
}
```

> Also, why is the option called least? Is that a good name to describe it?

Maybe `as-needed` be better or not?
