### ISSUE TITLE
Rule idea: color-no-non-variables

### ISSUE THREAD

**Issue by davidtheclark** [kristerkari/stylelint-scss#4]
Someone may want to enforce that any color values are named and reused as variables.

This can make the code more legible and DRY.

```scss
// bad
.foo { color: pink; background: #fff; }

// good
$some-color: pink;
$some-background: #fff;
.foo { color: $some-color; background: $some-backgorund; }
```
