### ISSUE TITLE
unit-whitelist exceptions in values

### ISSUE THREAD

**Issue by alejandroclaro** [kristerkari/stylelint-scss#474]
> What is the problem you're trying to solve?

Define unit-whitelist or unit-blacklist exceptions based on the type and name of a value, and if possible based on a selector. We want to restrict the use of absolute units (prefer relative units in some cases), but of course, it's needed to establish a base case using absolute units. 

This is one example:

```scss
html {
  font-size: 16px;
  font-size: 16px; /* stylelint-disable-line unit-whitelist */
}

`/* stylelint-disable unit-whitelist */`
$breakpoints: (
  "extra-small": ("width": 800px, "height": 600px),
  "small": ("width": 1024px, "height": 800px),
  "medium": ("width": 1024px, "height": 1280px),
  "large": ("width": 1280px, "height": 1024px)
);
`/* stylelint-enable unit-whitelist */`

$disabled: (
    border-radius: .25rem,
    border-width: .063rem,
    border-radius: 0.25rem,
    border-width: 0.063rem,
    box-shadow: 0 .063rem .063rem 0 $gray-50
    box-shadow: 0 0.063rem 0.063rem 0 $gray-50
);
```

I would like to add exceptions to the rules instead of introducing comments to silent the validations.  Here I could add an exception for property 'width', but that will affect all the occurrences of 'width' property, and that's not what we want. We just want to allow the use of absolute units in the properties inside the definition of '$breakpoint' for example.

I already communicate with the stylelint team, and they told me that this plugin is the best place to ask for this feature since one of the cases we have is related to a SASS map ($breakpoints).

>  What solution would you like to see?

Add a mechanism to add exception based on the "type" and/or "name" of values, or "based" on selectors.
