### ISSUE TITLE
[Bug] `+` operator on scss/selector-no-redundant-nesting-selector

### ISSUE THREAD

**Issue by Mister-Hope** [kristerkari/stylelint-scss#520]
![image](https://user-images.githubusercontent.com/33315834/117290152-0792e580-aea0-11eb-8388-26fa8f722ef8.png)

For a nested selector,  `& + &` won't work.

```html
<div class="a">
   <div class="b">test</div>
   <div class="b">test</div>
</div>
```

```scss
.a{
  .b{
     // won't work
     & + &{
     color: #f00;
    }
    // will work
    // & + .b{
    //  color: #f00;
    // }
  }
}
```

See https://codepen.io/mister-hope/pen/XWKwgBm
