### ISSUE TITLE
Check and update all rules to consider nested props

### ISSUE THREAD

**Issue by dryoma** [kristerkari/stylelint-scss#62]
Like in
```scss
.funky {
  font: 20px/#{$font-size*1.2} fantasy { // operator-no-unspaced should warn
    weight: bold;
  }
}
```
